name: .NET
on:
  push:
    branches: [ "main" ]
    paths: 
       - './PostsService/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - './PostsService/**'

defaults:
 run:
   working-directory: ./PostsService

jobs:
  build:
    runs-on: ubuntu-latest
    
    # defaults:
    #   run:
    #     working-directory: ./PostsService

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      #working-directory: ./PostsService
      run: dotnet restore
    - name: Build
      #working-directory: ./PostsService
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  # test:
  #   runs-on: ubuntu-latest
    
  #   defaults:
  #     run:
  #       working-directory: ./PostsService
    
  #   needs: build
  #   steps:
